<a href="https://colab.research.google.com/github/Awan-sang-hengker/Aljabar-Matriks/blob/main/Data_Structure_for_algebra_Soal_1_2_(Vectors_and_Vector_Transposition).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soal 1

In [1]:
import numpy as np

In [3]:
#buat vector x dengan ukuran 3x1
x = np.array([76, 67, 12])
x

array([76, 67, 12])

In [4]:
#hitung panjang vector x
len(x)

3

In [5]:
#tampilkan ukuran vector x
x.shape

(3,)

In [6]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [7]:
#akses elemen pertama dari vector x
x[0]

np.int64(76)

In [8]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

Soal 2

In [9]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_trans = x.T
x_trans

array([76, 67, 12])

In [11]:
#tampilkan ukuran dari vector x_t
x_trans.shape

(3,)

In [14]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[76],
              [67],
              [12]])
y

array([[76],
       [67],
       [12]])

In [15]:
#tampilkan ukuran dari vector x_t
y.shape

(3, 1)