<a href="https://colab.research.google.com/github/Awan-sang-hengker/Aljabar-Matriks/blob/main/Data_Structure_for_algebra_Soal_1_2(Matrix_Tensors).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soal 1

In [1]:
import numpy as np

In [6]:
import torch

In [19]:
import tensorflow as tf

In [21]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[1, 2, 3], [67, 76, 97]])
X

array([[ 1,  2,  3],
       [67, 76, 97]])

In [22]:
#tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [23]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([ 1, 67])

In [24]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([67, 76, 97])

Soal 2

In [11]:
#ulangi soal nomor 1 menggunakan pytorch

In [25]:
#buat matrix X_pt berukuran 2x3 menggunakan numpy (Pytorch)
X_pt = torch.tensor([[1, 2, 3], [67, 76, 97]])
X_pt

tensor([[ 1,  2,  3],
        [67, 76, 97]])

In [26]:
#tampilkan ukuran dari matrix X_pt
X_pt.shape

torch.Size([2, 3])

In [27]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X_pt
X_pt[:,0]

tensor([ 1, 67])

In [28]:
#tampilkan seluruh elemen dari baris kedua dari matrix X_pt
X_pt[1,:]

tensor([67, 76, 97])

In [29]:
#ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.Variable([[1, 2, 3], [67, 76, 97]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [67, 76, 97]], dtype=int32)>

In [31]:
#tampilkan ukuran dari matrix X_tf
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [32]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 67], dtype=int32)>

In [33]:
#tampilkan seluruh elemen dari baris kedua dari matrix X_tf
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([67, 76, 97], dtype=int32)>