<a href="https://colab.research.google.com/github/Awan-sang-hengker/Aljabar-Matriks/blob/main/Data_Structure_for_algebra_Soal_3_(Vectors_and_Vector_Transposition).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Soal 3

In [1]:
import numpy as np

In [3]:
import tensorflow as tf

In [14]:
import torch

In [9]:
#lakukan soal nomor 2 menggunakan pytorch dan tensorflow

Tensorflow

In [15]:
#lakukan transpose pada vector x dan simpan pada variabel x_tf (Tensorflow)
x_tf = tf.Variable([[10],
                    [15],
                    [20]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[10],
       [15],
       [20]], dtype=int32)>

In [16]:
#tampilkan ukuran dari vector x_tf (Tensorflow)
x_tf.shape

TensorShape([3, 1])

In [18]:
#lakukan transpose pada vector y dan simpan pada variabel y_tf (Tensorflow)
y_tf = tf.Variable([[10],
                    [15],
                    [20]])
y_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[10],
       [15],
       [20]], dtype=int32)>

In [19]:
#tampilkan ukuran dari vector y_tf (Tensorflow)
y_tf.shape

TensorShape([3, 1])

Pytorch

In [20]:
#lakukan transpose pada vector x dan simpan pada variabel x_pt (Pytorch)
x_pt = torch.tensor([[10],
                    [15],
                    [20]])
x_pt

tensor([[10],
        [15],
        [20]])

In [21]:
#tampilkan ukuran dari vector x_pt (Pytorch)
x_pt.shape

torch.Size([3, 1])

In [22]:
#lakukan transpose pada vector y dan simpan pada variabel y_pt (Pytorch)
y_pt = torch.tensor([[10],
                    [15],
                    [20]])
y_pt

tensor([[10],
        [15],
        [20]])

In [23]:
#tampilkan ukuran dari vector y_pt (Pytorch)
y_pt.shape

torch.Size([3, 1])